create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  name text not null,
  mobile text not null,
  ward text not null,
  area text not null,
  category text not null,
  message text not null,
  consent boolean not null default false,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

alter table public.feedback enable row level security;

-- No public table policies are required. The website writes and reads only
-- through protected server routes using SUPABASE_SERVICE_ROLE_KEY.
