"use client";
import { useEffect, useState } from "react";
import { ArrowLeft, CheckCircle2, Send } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";

export default function FeedbackPage(){
 const [done,setDone]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [dateTime,setDateTime]=useState("");
 useEffect(()=>{const update=()=>setDateTime(new Date().toLocaleString("hi-IN",{timeZone:"Asia/Kolkata",dateStyle:"full",timeStyle:"short"}));update();const timer=setInterval(update,30000);return()=>clearInterval(timer)},[]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);const payload:Record<string,FormDataEntryValue|boolean>=Object.fromEntries(f);payload.consent=f.get("consent")==="on";const r=await fetch("/api/feedback",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();setBusy(false);if(r.ok)setDone(true);else setError(d.error||"कृपया दोबारा प्रयास करें।");}
 if(done)return <main className="grid min-h-screen place-items-center bg-[#f6f3ea] p-5"><div className="max-w-md rounded-[2rem] bg-white p-10 text-center shadow-xl"><CheckCircle2 className="mx-auto size-14 text-[#23845d]"/><h1 className="mt-5 text-3xl font-semibold text-[#17352c]">फीडबैक दर्ज हो गया</h1><p className="mt-3 leading-7 text-[#587068]">धन्यवाद! आपकी जानकारी सुरक्षित रूप से भेज दी गई है।</p><p className="mt-4 rounded-xl bg-[#f6f3ea] p-3 text-sm font-medium text-[#587068]">{dateTime}</p><p className="mt-4 text-sm text-[#587068]">अब आप यह पेज बंद कर सकते हैं।</p></div></main>;
 return <main className="min-h-screen bg-[#f6f3ea] px-5 py-8 text-[#17352c]"><div className="mx-auto max-w-2xl"><button onClick={()=>history.back()} className="inline-flex items-center gap-2 text-sm text-[#587068]"><ArrowLeft className="size-4"/> वापस</button><div className="mt-6 rounded-[2rem] bg-white p-6 shadow-xl sm:p-10"><p className="text-sm font-semibold text-[#df7b2f]">जन संवाद फॉर्म</p><h1 className="mt-2 text-3xl font-semibold">अपनी समस्या या सुझाव साझा करें</h1><p className="mt-3 text-sm leading-6 text-[#587068]">* चिह्नित जानकारी जरूरी है। आपका मोबाइल नंबर सार्वजनिक नहीं किया जाएगा।</p><div className="mt-5 rounded-xl border border-[#17352c]/10 bg-[#f6f3ea] px-4 py-3"><p className="text-xs font-semibold uppercase tracking-wider text-[#df7b2f]">Automatic Date & Time</p><p className="mt-1 text-sm font-medium">{dateTime || "समय लोड हो रहा है..."}</p></div><form onSubmit={submit} className="mt-8 grid gap-5 sm:grid-cols-2"><div><Label htmlFor="name">नाम *</Label><Input id="name" name="name" required maxLength={80} className="mt-2 h-12" placeholder="आपका नाम"/></div><div><Label htmlFor="mobile">मोबाइल नंबर *</Label><Input id="mobile" name="mobile" required inputMode="tel" pattern="[+0-9 ]{10,15}" className="mt-2 h-12" placeholder="10 अंकों का नंबर"/></div><div><Label>वार्ड नंबर *</Label><Select name="ward" required><SelectTrigger className="mt-2 h-12 w-full"><SelectValue placeholder="वार्ड चुनें"/></SelectTrigger><SelectContent>{Array.from({length:45},(_,i)=>i+1).map(n=><SelectItem key={n} value={`वार्ड ${n}`}>वार्ड {n}</SelectItem>)}</SelectContent></Select></div><div><Label htmlFor="area">मोहल्ला / स्थान *</Label><Input id="area" name="area" required className="mt-2 h-12" placeholder="जैसे: मुख्य बाजार"/></div><div className="sm:col-span-2"><Label>विषय *</Label><Select name="category" required><SelectTrigger className="mt-2 h-12 w-full"><SelectValue placeholder="विषय चुनें"/></SelectTrigger><SelectContent>{["सड़क","पानी","सफाई","स्ट्रीट लाइट","स्वास्थ्य","अन्य सुझाव"].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div><div className="sm:col-span-2"><Label htmlFor="message">समस्या / सुझाव *</Label><Textarea id="message" name="message" required minLength={5} maxLength={800} className="mt-2 min-h-32" placeholder="अपनी बात विस्तार से लिखें..."/></div><input name="website" className="hidden" tabIndex={-1} autoComplete="off"/><div className="flex gap-3 sm:col-span-2"><Checkbox id="consent" name="consent"/><Label htmlFor="consent" className="font-normal leading-5 text-[#587068]">जरूरत पड़ने पर इस विषय में मुझसे संपर्क किया जा सकता है।</Label></div>{error&&<p className="text-sm text-red-600 sm:col-span-2">{error}</p>}<Button disabled={busy} className="h-12 rounded-full bg-[#17352c] sm:col-span-2">{busy?"दर्ज हो रहा है...":<>फीडबैक भेजें <Send className="ml-2 size-4"/></>}</Button></form></div></div></main>
}
