"use client";
import { useState } from "react";
import { Download, Inbox, MapPin, MessageSquareText, Phone } from "lucide-react";
import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

type Feedback = { id:number; name:string; mobile:string; ward:string; area:string; category:string; message:string; status:string; createdAt:string };

export default function InboxPage(){
 const [pin,setPin]=useState(""); const [rows,setRows]=useState<Feedback[]|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 async function openInbox(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");const r=await fetch("/api/admin/feedback",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({pin})});const d=await r.json();setBusy(false);if(r.ok)setRows(d.feedback);else setError(d.error||"Inbox नहीं खुल पाया।");}
 function downloadCsv(){if(!rows?.length)return;const cell=(value:unknown)=>`"${String(value??"").replaceAll('"','""')}"`;const header=["क्रमांक","नाम","मोबाइल नंबर","वार्ड","मोहल्ला / स्थान","विषय","फीडबैक","स्थिति","दिनांक और समय"];const data=rows.map((x,i)=>[i+1,x.name,x.mobile,x.ward,x.area,x.category,x.message,x.status,new Date(x.createdAt.replace(" ","T")+"Z").toLocaleString("hi-IN")]);const csv="\uFEFF"+[header,...data].map(row=>row.map(cell).join(",")).join("\r\n");const blob=new Blob([csv],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`jan-samvad-feedback-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url);}
 if(rows===null)return <main className="grid min-h-screen place-items-center bg-[#17352c] p-5"><form onSubmit={openInbox} className="w-full max-w-sm rounded-3xl bg-white p-8 text-[#17352c] shadow-xl"><Inbox className="size-8 text-[#df7b2f]"/><h1 className="mt-4 text-2xl font-semibold">Admin Inbox</h1><p className="mt-2 text-sm text-[#587068]">फीडबैक देखने के लिए Admin PIN डालें।</p><Input value={pin} onChange={e=>setPin(e.target.value)} type="password" inputMode="numeric" required className="mt-6 h-12" placeholder="Admin PIN"/>{error&&<p className="mt-3 text-sm text-red-600">{error}</p>}<Button disabled={busy} className="mt-3 h-12 w-full rounded-full bg-[#17352c]">{busy?"Inbox खुल रहा है...":"Inbox खोलें"}</Button></form></main>;
 return <main className="min-h-screen bg-[#eef1ed] p-5 text-[#17352c] sm:p-8"><div className="mx-auto max-w-6xl"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-[#df7b2f]">जन संवाद प्रशासन</p><h1 className="mt-1 flex items-center gap-3 text-3xl font-semibold"><Inbox className="size-8"/> Feedback Inbox</h1></div><div className="flex flex-wrap gap-2"><Button onClick={downloadCsv} disabled={!rows.length} className="rounded-full bg-[#df7b2f] hover:bg-[#c96d27]"><Download className="mr-2 size-4"/> CSV / Excel Download</Button><Link href="/qr" className="rounded-full bg-[#17352c] px-5 py-2.5 text-sm font-medium text-white">QR देखें</Link></div></header><section className="mt-7 grid gap-4 sm:grid-cols-3"><Stat label="कुल फीडबैक" value={rows.length}/><Stat label="नए संदेश" value={rows.filter(x=>x.status==="new").length}/><Stat label="वार्ड" value={new Set(rows.map(x=>x.ward)).size}/></section><div className="mt-7 space-y-4">{rows.length===0?<Empty text="अभी कोई फीडबैक प्राप्त नहीं हुआ है।"/>:rows.map(x=><article key={x.id} className="rounded-2xl border border-[#17352c]/10 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold">{x.name}</h2><Badge className="bg-[#fff1d8] text-[#9b631c] hover:bg-[#fff1d8]">{x.category}</Badge><Badge variant="outline">{x.ward}</Badge></div><div className="mt-2 flex flex-wrap gap-4 text-xs text-[#587068]"><span className="flex items-center gap-1"><Phone className="size-3"/>{x.mobile}</span><span className="flex items-center gap-1"><MapPin className="size-3"/>{x.area}</span></div></div><time className="text-xs text-[#7a8e86]">{new Date(x.createdAt.replace(" ","T")+"Z").toLocaleString("hi-IN",{dateStyle:"medium",timeStyle:"short"})}</time></div><p className="mt-4 flex gap-2 rounded-xl bg-[#f6f3ea] p-4 text-sm leading-6"><MessageSquareText className="mt-0.5 size-4 shrink-0 text-[#df7b2f]"/>{x.message}</p></article>)}</div></div></main>
}
function Stat({label,value}:{label:string,value:number}){return <div className="rounded-2xl bg-[#17352c] p-5 text-white"><p className="text-sm text-white/65">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></div>}
function Empty({text}:{text:string}){return <div className="rounded-3xl border border-dashed border-[#17352c]/20 bg-white p-14 text-center text-[#587068]">{text}</div>}
